# Generated by Django 2.2.16 on 2020-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200924_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
